[package]
name = "syng-dictionary-creator"
version = "1.1.1"
authors = ["Preston Wang-Stosur-Bassett <p.wanstobas@gmail.com>"]

[dependencies]
serde = "1.0.14"
serde_json = "1.0.3"
serde_derive = "1.0.14"
regex = "0.2"
prettify_pinyin = "1.0.1"
